-- AlterTable
ALTER TABLE "Product"
ADD COLUMN "costPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem"
ADD COLUMN "unitCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "profit" DOUBLE PRECISION NOT NULL DEFAULT 0;
